name: checks

on:
  push:
    branches: [main]
  pull_request:
  workflow_call:

jobs:
  checks:
    uses: Julien-R44/.github/.github/workflows/checks.yml@main
  test:
    uses: Julien-R44/.github/.github/workflows/test.yml@main
