name: Release

on:
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  checks:
    uses: ./.github/workflows/ci.yml

  release:
    needs: checks
    uses: Julien-R44/.github/.github/workflows/release.yml@main
    secrets: inherit
